on: [push]
name: build
jobs:
  build:
    name: Get Current Time
    runs-on: ubuntu-latest
    steps:
      - name: Get current Time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"